# Generated by Django 4.2.10 on 2024-02-24 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('descriptions', models.TextField(blank=True)),
                ('image', models.ImageField(default='classes/default_indir.jpeg', upload_to='classes/%Y/%m/%d/')),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
