# Generated by Django 4.2.10 on 2024-02-24 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='descriptions',
            new_name='description',
        ),
    ]
