# Generated by Django 4.2.10 on 2024-02-26 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_remove_class_students_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Class',
            new_name='Class_obj',
        ),
    ]
