# Generated by Django 4.2.10 on 2024-02-26 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0006_rename_class_class_obj'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class_obj',
            old_name='Category',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
