# Generated by Django 4.2.10 on 2024-02-27 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0010_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='class_obj',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='classes.tag'),
        ),
    ]
