# Generated by Django 4.2.10 on 2024-02-27 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0011_class_obj_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class_obj',
            name='tags',
        ),
    ]
