# Generated by Django 4.2.10 on 2024-02-27 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='about',
            name='date',
        ),
        migrations.RemoveField(
            model_name='about',
            name='image',
        ),
    ]
