# Generated by Django 4.2.10 on 2024-02-28 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_rename_name_about_title_remove_about_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='image',
            field=models.ImageField(default='classes/default_indir.jpeg', upload_to='classes/%Y/%m/%d/'),
        ),
    ]
