# Generated by Django 4.2.10 on 2024-02-28 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_about_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('comment', models.TextField()),
                ('image', models.ImageField(default='classes/default_indir.jpeg', upload_to='classes/%Y/%m/%d/')),
            ],
        ),
    ]
