# Generated by Django 4.2.10 on 2024-02-28 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_studentreview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentreview',
            name='comment',
        ),
        migrations.AddField(
            model_name='studentreview',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
