# Generated by Django 4.2.10 on 2024-02-29 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_remove_studentreview_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentreview',
            name='image',
            field=models.ImageField(default='classes/default_indir.jpeg', upload_to='StudentReview/%Y/%m/%d/'),
        ),
    ]
